spring.application.name=reportes
server.port=8087

server.address=0.0.0.0
eureka.client.serviceUrl.defaultZone=http://26.227.33.49:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=26.111.237.70
eureka.instance.hostname=26.111.237.70
eureka.instance.instance-id=${spring.application.name}:${eureka.instance.ip-address}:${server.port}

